### ISSUE TITLE
How to train the new dataset in the code?  

### ISSUE THREAD

**Issue by KYRA-ma** [meteahishali/SRL-SOA#5]
I just want to change the dataset to run the demo. But there is no weights corresponding to the referred dataset. How could I train on the new dataset. I've tried hard, but it always goes wrong.

Could you give me some suggestion?

**Comment by KYRA-ma** [comment]
![image](https://github.com/meteahishali/SRL-SOA/assets/100602358/4a1d82a1-17f0-49aa-8624-a08dda5cb38d)

**Comment by KYRA-ma** [comment]
![image](https://github.com/meteahishali/SRL-SOA/assets/100602358/919e47ed-a7d5-4dae-8550-3e7c52d736a7)
How to fix this problem

**Comment by meteahishali** [comment]
Hi,

Thanks for your interest in our work. So, you just need to load the new dataset in utils.py script lines 21-33.

```python
def loadData(dataset):
    Data = scipy.io.loadmat('data/' + dataset + '.mat')
    if 'Indian' in dataset: Gtd = scipy.io.loadmat('data/' + 'Indian_pines_gt.mat')
    elif 'SalinasA' in dataset: Gtd = scipy.io.loadmat('data/' + 'SalinasA_gt.mat')
    else: Gtd = scipy.io.loadmat('data/' + dataset + '_gt.mat')

    if dataset == 'Indian_pines_corrected':
        image = Data['indian_pines_corrected']
        gtd = Gtd['indian_pines_gt']
    elif dataset == 'SalinasA_corrected':
        image = Data['salinasA_corrected']
        gtd = Gtd['salinasA_gt']
    else: print('The selected dataset is not valid.')
``` 

Of course based on how you organize labels in your dataset, you may need to make additional changes in the loadData function.

**Comment by meteahishali** [comment]
I am closing this issue due to the inactivity.
