### ISSUE TITLE
BandSection包安装不了

### ISSUE THREAD

**Issue by wzd88766** [meteahishali/SRL-SOA#6]
如何在pycharm中配置BandSecton这个包
<img width="962" alt="Snipaste_2023-11-28_23-49-24" src="https://github.com/meteahishali/SRL-SOA/assets/151824840/ac2a9cba-cbd2-4d53-9b4e-9a6d1947e50e">

**Comment by meteahishali** [comment]
You can get the compared methods as follows,
```
git clone https://github.com/AngryCai/BandSelection.git
git clone https://github.com/AngryCai/GCSR-BS
mv -f GCSR-BS/ GCSR_BS/
```

Best Regards,
Mete Ahishali

**Comment by meteahishali** [comment]
I am closing this issue due to the inactivity.
